### ISSUE TITLE
Replace with native C extension

### ISSUE THREAD

**Issue by pansimey** [markburns/mecab#6]
@markburns Thanks for suggesting in tadd/mecab-heavy@3054de395cc9519ec4417012026395b3545bfefe . 

I have been working on MeCab C extension in [MeCab::Light](https://github.com/hadzimme/mecab-light).
How about sorting problems/tasks in bringing a part of its results?

Let me quote Mark's saying:

> > I'm wondering which class should have #each method
> 
> I'll spend a bit of time trying to really grok some of that stuff and your C extension file. It looks a lot more accessible than the SWIG stuff. Then I can at least give my thoughts on what the ruby API should/could look like. In the meantime, feel free to consider a pull request.
> 
> > e.g. #sentence= instead of #set_sentence
> 
> I like #sentence= much more than #set_sentence.
> 
> > I'm afraid of confusing existing users
> 
> I would suggest we use a major version change for those changes, or probably more likely support both.
> 
> I've chosen an unfortunate version numbering system following the mecab C library versioning.
> Which means I'll have to abandon that (I figured that would happen anyway). If we abandon it then we can choose a different way to refer to the mecab version. Which makes more sense.
> 
> > I have left some memory leak problems (but still must be better than SWIG version)
> 
> I'll take your word on this, and/or advice on what to improve.

**Comment by pansimey** [comment]
But I found @mrkn has already written super cool C extension.
https://github.com/mrkn/mecaby

**Comment by keichan34** [comment]
I've been playing around with the idea of using Ruby FFI instead of using a C extension at all -- we were having some problems installing the library and headers correctly, so this kind of approach would (theoretically) make it a lot easier.

https://github.com/keichan34/mecab_ffi
